[tools]
bun = "latest"
chezmoi = "latest"
claude = { version = "latest", bin = "claude", platforms = """
[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", url = 'https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/{{ os(macos="darwin") }}-{{ arch() }}/claude', version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
ctop = "latest"
deno = "latest"
fastfetch = "latest"
fzf = "latest"
"github:anomalyco/opencode" = "latest"
"github:trasta298/keifu" = "latest"
go = "latest"
helix = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@github/copilot" = "1.0.10"
"npm:@openai/codex" = "latest"
"npm:typescript-language-server" = "latest"
pnpm = "latest"
python = "3.13"
rg = "latest"
rust = "latest"
uv = "latest"
wrangler = "latest"
yazi = "latest"
zig = "latest"
zls = "latest"
zoxide = "latest"
"npm:typescript" = "latest"
"npm:vscode-html-languageserver-bin" = "latest"
atuin = "latest"
bat = "latest"
codex = "latest"
java = "latest"
"github:zellij-org/zellij" = "latest"
"npm:skills" = "latest"


# [tasks.sync-dotfiles]
# shell = "powershell"
# run = "chezmoi managed | Where-Object { -not (Test-Path (Join-Path $HOME $_) -PathType Container) } | ForEach-Object { chezmoi re-add (Join-Path $HOME $_) }; cd $HOME/.local/share/chezmoi; git add .; git commit -m \"Sync\"; git push"

[tasks.sync-dotfiles]
shell = "powershell"
run = "foreach ($f in (chezmoi managed)) { if (-not (Test-Path (Join-Path $HOME $f) -PathType Container)) { chezmoi re-add (Join-Path $HOME $f) } }; Write-Host '===== GIT diff ====='; git -C \"$HOME/.local/share/chezmoi\" diff; if (git -C \"$HOME/.local/share/chezmoi\" diff --quiet) { Write-Host 'No changes. Skip commit/push.'; exit 0 }; cd \"$HOME/.local/share/chezmoi\"; git add .; git commit -m 'Sync'; git push"
