theme = "catppuccin_mocha"

[keys.normal]
C-y = ":sh powershell -NoProfile -ExecutionPolicy Bypass -File C:\\Users\\megab\\AppData\\Roaming\\helix\\yazi-picker.ps1"


# [keys.normal]
# C-y = ":sh zellij action new-pane -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- powershell -NoProfile -ExecutionPolicy Bypass -File C:\\Users\\megab\\AppData\\Roaming\\helix\\yazi-picker.ps1"
