theme = "catppuccin_mocha"

# [keys.normal]
# C-y = "zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- powershell -NoProfile -ExecutionPolicy Bypass -File %appdata%helix\yazi-picker.ps1\""

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
language-servers = ["html-languageserver"]

[[language]]
name = "css"
language-servers = ["css-languageserver"]

[[language]]
name = "json"
language-servers = ["json-languageserver"]

[[language]]
name = "lua"
language-servers = ["lua-language-server"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "go"
language-servers = ["gopls"]

[[language]]
name = "c"
language-servers = ["clangd"]

[[language]]
name = "cpp"
language-servers = ["clangd"]

[[language]]
name = "java"
language-servers = ["jdtls"]

[[language]]
name = "ruby"
language-servers = ["solargraph"]

[[language]]
name = "php"
language-servers = ["intelephense"]

[[language]]
name = "markdown"
language-servers = ["markdownlint"]

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[[language]]
name = "toml"
language-servers = ["taplo"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[[language]]
name = "dockerfile"
language-servers = ["dockerfile-language-server"]
